services:
  - type: web
    name: pokemon
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: true

databases:
  - name: db-pokemon
    plan: free
