services:
  - type: web
    name: smartsleep-pokemon
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: true

databases:
  - name: pokemon-db
    plan: free
